branches:
  only:
    - master
services:
  - mongodb
  - redis-server
rvm:
  - 1.9.2
  - 1.9.3
  - rbx-19mode
  - jruby-19mode
script: bundle exec rspec spec
notifications:
  email:
    - ethan.turkeltaub@gmail.com